### ISSUE TITLE
Unit 1: Lesson 2 enhancements

### ISSUE THREAD

**Issue by ppekrol** [ravendb/bootcamp#10]
- "A document store is the main client API object, which establishes..."
  Maybe add some links to the documentation in couple of places e.g. you can add at the end "You can read more in our documentation [here]()". You can use http://ravendb.net/docs/article-page/latest/csharp/client-api/what-is-a-document-store and I will ensure that this will redirect to the latest docs. I do not think that we should tie up to the 3.0 and most of basic articles will probably not move ever so it should be safe to use /latest/

Not saying that this should be done in this particular place but some people might be interested in more details sometimes.
- "By convention, the document Id is stored in the Id property."  
  I think that it is a bit unclear what you mean here.

**Comment by ElemarJR** [comment]
Add references to the documentation is an excellent idea. We just have to define some decision criteria to  when and how use it.

Do you have any suggestion?

**Comment by ppekrol** [comment]
Not really, just "be reasonable" is the best I can give you. I will be reviewing today other lessons and will leave you markers for docs so you will be able to consider having them there or not.
