### ISSUE TITLE
Loading different object types with a single Load command

### ISSUE THREAD

**Issue by vmrocha** [ravendb/bootcamp#30]
In **Unit 1, Lesson 4 - Loading documents**, in the exercise to load multiple documents with a single Load call, the sample code is not working as expected on the current version, 3.5.1.

More specifically the following code:

```csharp
object[] items = session.Load<object>("products/1", "categories/2");

Product p = (Product) items[0];
Category c = (Category) items[1];
```

The first line is not compiling, I had to change it to:

```csharp
object[] items = session.Load<object>(new[] { "products/1", "categories/2" });
```

The other two lines throws an **InvalidCastException**. Additional information: **Unable to cast object of type 'Raven.Abstractions.Linq.DynamicJsonObject' to type 'Northwind.Product'**.

**Comment by tmpreston** [comment]
Running into same issue above. RavenDB client 3.5.3.0.

**Comment by ayende** [comment]
`object[] items = session.Load<object>("products/1", "categories/2");` should call https://github.com/ravendb/ravendb/blob/v3.5/Raven.Client.Lightweight/IDocumentSession.cs#L112, but that is only for value types. Using the array will make it call https://github.com/ravendb/ravendb/blob/v3.5/Raven.Client.Lightweight/IDocumentSession.cs#L125

The error then has to do with missing `Raven-Clr-Type` on the class, which is something that you can fix by loading and saving the document (which will fix the metadata value).
We'll fix this.
