### ISSUE TITLE
Unit 2, Lesson 2 AddressClass definition

### ISSUE THREAD

**Issue by ysc0423** [ravendb/bootcamp#41]
Unit 2, Lesson 2
AddressClass 
PostalCode should be string.

**Comment by ayende** [comment]
@ysc0423 That actually depend on your location. In London, certainly, in Israel, a number would suffice.

**Comment by satishfied** [comment]
I am also agree with Ayende Rahien. If you follow the steps mentioned in tutorial, you will get proper class definition.
