### ISSUE TITLE
Not able to find CreateSession() method

### ISSUE THREAD

**Issue by satishfied** [ravendb/bootcamp#42]
Hi

I am learning RavenDB through bootcamp and I am enjoying it.

Under Unit 1: Fundamentals Lesson 6: Storing, modifying and deleting documents, there is a section 
"**Modifying documents with the Store method**"

There is a code 

var (session = DocumentStoreHolder.Store.CreateSession())
        {
            session.Store(category);
            session.SaveChanges();
        }

In above mention code there is CreateSession() method, but I am not able to find it while implementing the same code in my project. I think it should be OpenSession().

**Comment by ayende** [comment]
Thanks, you are correct, fixed.
