### ISSUE TITLE
Missing Prompt in DeleteContact()

### ISSUE THREAD

**Issue by satishfied** [ravendb/bootcamp#43]
Hi,

There is no prompt for "**contact id**" in Unit 1, Lesson 6 - Storing, modifying and deleting documents demo code.

private void DeleteContact()
{
    var id = Console.ReadLine();
    using (var session = DocumentStoreHolder.Store.OpenSession())
    {
        var contact = session.Load<Contact>(id);

        if (contact == null)
        {
            Console.WriteLine("Contact not found.");
            return;
        }

        session.Delete(contact);
        session.SaveChanges();
    }
}

There should be prompt at first line of method as follow

 Console.WriteLine("Enter the contact id");

**Comment by ayende** [comment]
Thanks, fixed
