### ISSUE TITLE
Unit 3, Lesson 4: Had to install additional package

### ISSUE THREAD

**Issue by zurfluh** [ravendb/bootcamp#44]
```
Install-Package System.Reactive.Linq
```
I had to install the package above in order for the code to compile.
(VS 2015, .NET 4.6.1)

Assuming that the error is consistent across platforms, could you change "Step 1" of the second exercise?

**Comment by satishfied** [comment]
Same happened with me also. I am agree with @zurfluh  suggestions.

**Comment by ayende** [comment]
Thanks, updated
