### ISSUE TITLE
Unit 3, Lesson 4: Etag Changes do not increment by 1

### ISSUE THREAD

**Issue by zurfluh** [ravendb/bootcamp#45]
Environment:
**RavenDB.Client 3.5.4
.NET 4.6.1**

The 2nd exercise assumes that any server change increments the Etag Changes by 1:
```
var numberOfServerChanges =
        change.Etag.Changes - _localEtag.Changes;
```
I observe however the Etag being incremented by 13 (if either Name or Description is changed) or by 26 (if both fields are changed).

I would be interested to understand the cause of the behavior. Further complicating the number magic in the application seems not to be a nice solution.

**Comment by satishfied** [comment]
Hi,

Same thing I also observed. Please make me understand what exactly it means.

Thanks
Satish Yeole

**Comment by ayende** [comment]
The only actual guarantees we give WRT to the etag changes is that it will go increment in value, not by how much it will go up.

**Comment by zurfluh** [comment]
Okay, thank you @ayende, this is what I assumed. Now the behavior of the example application seems not to be correct.

The unknown etag increment means that the function `DocumentChangedByOtherUser(...)` (EditCategoryForm.cs) returns `true` even when the document was not changed by another user. So the `DocumentChangedOnServer(...)` method is called every time I change something in my local instance, and it says, "Document was changed on the server. Would you like to refresh?" This is misleading. I think we need to find another way to check whether the document was changed by another user.

**Comment by ElemarJR** [comment]
@zurfluh thanks. Working on that.
