### ISSUE TITLE
Unit 1, Lesson 5, Step 5

### ISSUE THREAD

**Issue by ghost** [ravendb/bootcamp#47]
RavenDB 3.5.4
RavenDB.Client 3.5.4

```c#
var orders = (
            from order in session.Query<Order>()
                                    .Include(o => o.Company)
            where order.Company == $"companies/{companyId}"
            select order
            ).ToList();
```

> Error	1	'Raven.Client.Linq.IRavenQueryable<Unit1_Lesson5.Order>' does not contain a definition for 'Include' and no extension method 'Include' accepting a first argument of type 'Raven.Client.Linq.IRavenQueryable<Unit1_Lesson5.Order>' could be found (are you missing a using directive or an assembly reference?)

**Comment by ayende** [comment]
Include `using Raven.Client; using Raven.Client.Linq;` at the top, what happens?

**Comment by ghost** [comment]
My bad. It was `using Raven.Client;`
