### ISSUE TITLE
Exception in sample code!

### ISSUE THREAD

**Issue by sadeghhp** [ravendb/bootcamp#48]
in the simplest start sample I have this error :

> ArgumentNullException: String reference not set to an instance of a String. Parameter name: s

`var documentStore = new DocumentStore
	{
		Url = "http://localhost:8080/",
		DefaultDatabase = "Northwind"
	};
	documentStore.Initialize();
	using (var session = documentStore.OpenSession())
	{
		var p = session.Load<Product>("products/77-A");
		p.Dump();
	}`

http://localhost:8080/databases/Northwind/queries/?&id=products/77-A&id=products/2&id=products/3
`{
Error: "Raven.Client.Exceptions.Routing.RouteNotFoundException: There is no handler for path: GET /databases/Northwind/queries/?&id=products/77-A&id=products/2&id=products/3 at Raven.Server.Routing.RequestRouter.<HandlePath>d__5.MoveNext() in C:\Builds\RavenDB-4.0-RC\src\Raven.Server\Routing\RequestRouter.cs:line 50 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult() at Raven.Server.RavenServerStartup.<RequestHandler>d__11.MoveNext() in C:\Builds\RavenDB-4.0-RC\src\Raven.Server\RavenServerStartup.cs:line 159",
Message: "There is no handler for path: GET /databases/Northwind/queries/?&id=products/77-A&id=products/2&id=products/3",
Type: "Raven.Client.Exceptions.Routing.RouteNotFoundException",
Url: "/databases/Northwind/queries/?&id=products/77-A&id=products/2&id=products/3"
}`

**Comment by ayende** [comment]
What build are you using here?
It looks like you are using the 3.5 client to talk to a 4.0 server.

**Comment by sadeghhp** [comment]
it looks the nuget package is not updated yet!

**Comment by ayende** [comment]
@gregolsky Can you look at this?

**Comment by gregolsky** [comment]
@sadeghhp The package for 4.0 is here (it's listed in prerelease versions): 
https://www.nuget.org/packages/RavenDB.Client/4.0.0-rc-40025

Please note while some of the code may work with 4.0, bootcamp content is meant to be used with RavenDB 3.5 . We are in the process of updating it.
