### ISSUE TITLE
Doesn't work at all in .net core 2.0

### ISSUE THREAD

**Issue by samcov** [ravendb/bootcamp#49]
Running code modified to work with the 4.02 client in .net core 2.0 results in: **The application is in break mode** exception before ever entering the source code. Commenting out any RavenDB code yields a working console app.

**If I switch to .net core 1.1, it works just fine**(with queries modified for my DB).

**Comment by gregolsky** [comment]
@samcov Please note while some of the code may work with 4.0, Bootcamp content is meant to be used with RavenDB 3.5 . We are in the process of updating it.

**Comment by samcov** [comment]
I know, as I said, I had to modify it for 4.02. The code isn't the issue, it's the client from nuget.

As soon as I use any client code, nothing works. The fact that it works perfectly in .net core 1.1 shows that 2.o causes the problem, IMO.

BTW, **where can I raise this issue with the RavenDB people**, I didn't see any issues on their github page?

**Comment by ppekrol** [comment]
Hi @samcov 

Can you push your changes to a branch and give us steps to reproduce?

P.

**Comment by samcov** [comment]
It's a VERY simple project and I've attached it here.

It's in a working state, however, you would have to modify urls, db's, etc to your liking.

To see the issue, change the project from dotnet 1.1 to 2.0, and whatever code you have won't matter, you'll never hit it.
[RavenDBTest.zip](https://github.com/ravendb/bootcamp/files/1764027/RavenDBTest.zip)

**Comment by ppekrol** [comment]
I've changed the csproj to:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="RavenDB.Client" Version="4.0.0" />
  </ItemGroup>

</Project>
```

and had issues with running the project but doing `dotnet restore` from cmd-line (not sure why sometimes the one built-in into VS does not trigger itself) and rebuilding resolved the problem and it is working now. Can you try that? I'm using VS2017 v15.5.7

**Comment by samcov** [comment]
**It works!!!** I'm also using VS2017 v15.5.7, and should have remembered that sometimes you need to go to the command line to get things to work.

I forget because most times VS gets it right, but sometimes... oh well, **Thanks for the help**!

This was important to me because we were deciding between Mongo & Raven, and my preference was Raven because it's just cleaner, IMO. Setup was beyond easy and the UI looks great.

**Comment by ppekrol** [comment]
No problem. The VS2017 can be a pain sometimes.

If you will have any questions ping us here or on our Google Groups: https://groups.google.com/forum/#!forum/ravendb
We are always happy to assist.
