### ISSUE TITLE
Unit 1, Lesson 6, Step 5 has a line of code that doesn't query for the full ID of the company

### ISSUE THREAD

**Issue by mdaguillo** [ravendb/bootcamp#64]
In Step 5, there's a line that attempts to load the company from the session cache:

`var company = session.Load<Company>(companyId);`

But the compiler complains because the companyId is an int (and even calling .ToString won't fix it cause it's not the full id). It looks like the RQL code portion has the correct line of code:

`var company = session.Load<Company>($"companies/{companyId}-A");`

Just wanted to give you a heads up to this so beginners don't get stuck thinking they did something wrong!

**Comment by ayende** [comment]
Thanks, I fixed this so it will use a string.
