### ISSUE TITLE
Unit 2, Lesson 4 , Setp 5

### ISSUE THREAD

**Issue by arthuraugsten** [ravendb/bootcamp#69]
Hello!

There is an error on this lesson!
The parameters Query<Products_ByCategory, Products_ByCategory.Result>() are inverted.

**Comment by ayende** [comment]
I'm not sure that I'm following. It has: `.Query<Products_ByCategory.Result, Products_ByCategory>()`, which is correct.
https://github.com/ravendb/bootcamp/blame/v4.x/src/unit2/lesson4/README.md#L178

You should have the DTO for the query and then the index, in that order
