### ISSUE TITLE
Unit 3, Lesson 4 Bulk update does not work

### ISSUE THREAD

**Issue by dmusic** [ravendb/bootcamp#70]
Hi there, 

First of all thank you for great bootcamp.

I am struggling getting Unit 3/Lesson 4 to work. My bulk updates don't really work.  Here is my code:

`var operation = DocumentStoreHolder.Store
                                               .Operations.Send(
                                new PatchByQueryOperation(@"from Product as p 
                                                            where p.Discontinued = false 
                                                            update 
                                                            {
                                                                p.PricePerUnit = p.PricePerUnit * 1.1
                                                            }"));`  

I can see request incoming and executing within traffic manager, but as well I can see that always 0 documents are affected (writing out message of BulkOperationResult).

Also when I try to execute similar update query from command window in RavenDB it provides errors:
`4:2 Expected end of query but got: update
Query: 
from Products as p
where p.Discontinued = false
and id() = "products/2-A"
update {
p.PricePerUnit = 21
}
Raven.Server.Documents.Queries.Parser.QueryParser+ParseException: 4:2 Expected end of query but got: update
` 
Client, Server, Studio version 4.2.2.

Could you please recommend what I miss here?

Thank you & best regards,
dmusic

**Comment by ppekrol** [comment]
Hi,

thank you for positive feedback regarding the bootcamp.

I think that you might be missing 's' in a collection name in your PatchByQueryOperation. It should be 'Products' not 'Product'. In RQL you need to specify the name of a collection, not the name of a single item.

Can you check if this is the case?

**Comment by dmusic** [comment]
Hi, 

Thanks, that was a problem. Just wondering: how can I do the same from RavenDB Studio? Seems update command is not existing.

**Comment by ppekrol** [comment]
You need to go to 'Patch' in Studio. I suspect that you are in 'Query'.

![image](https://user-images.githubusercontent.com/446555/63288119-3fb55780-c2bc-11e9-967c-ade304ffc99f.png)

**Comment by Jens-G** [comment]
Stupid mistake I just did myself  😂  ... but the error mesage is not overly helpful to be honest: Syntax error ...
