### ISSUE TITLE
Unit 4, Lesson 2 - Unable of creating new nodes in cluster

### ISSUE THREAD

**Issue by dmusic** [ravendb/bootcamp#71]
Hi there, 

I am trying to create new nodes in my cluster. I have installed RavenDB with Let's Encrypt Certificates and originally I have created only one node (node A) which is master in my DB server. In customer portal, I was able to create to additional nodes (B and C) and was able to start locally with server utility:

`.\Raven.Server.exe --ServerUrl=https://b.<mydomain> --ServerUrl.Tcp=tcp://b.<mydomain>:38889 --Logs.Path=Logs/B --DataDir=Data/B`

I have assigned separate local IP and I am able to test connection in RavenDB studio:

![image](https://user-images.githubusercontent.com/9210505/63725987-444db300-c85c-11e9-9b10-7c500def7760.png)

When I add node to cluster, it seems that all cores get assigned again to Node A:

![image](https://user-images.githubusercontent.com/9210505/63725866-ec16b100-c85b-11e9-809b-dbc1871ee9ba.png)

Node B is not setup. Same happens if I try to create 2 additional nodes and try to assign to every node only one core. I am using RavenDB 4.2.2 Community license.

Is this a bug or I miss something? Thank you for your support.

**Comment by ayende** [comment]
You can reduce the number of cores that you are using before adding a new node.  But it sounds like you did it already.
What is the actual error that you get?

**Comment by dmusic** [comment]
Hi Ayende, 

There were no errors. Just nothing happened and I still had only one node in a cluster.

**Comment by ayende** [comment]
You added a new node, and nothing happened? What exactly did you try to do?
