### ISSUE TITLE
Unit 2, Lesson 4 - Mapping, Filtering, and Reducing- Inconsistent accessibility error

### ISSUE THREAD

**Issue by gbellak** [ravendb/bootcamp#72]
Hi,

using your example: Exercise: Your First Map-Reduce Index
in Step 3: Write the Map-Reduce index definition

I get error: 
Inconsistent accessibility: base class 'AbstractIndexCreationTask<Product, Products_ByCategory.Result>' is less accessible than class 'Products_ByCategory'

It seems I need to remove "public" from Products_ByCategory class to make it work

**Comment by gbellak** [comment]
> Hi,
> 
> using your example: Exercise: Your First Map-Reduce Index
> in Step 3: Write the Map-Reduce index definition
> 
> I get error:
> Inconsistent accessibility: base class 'AbstractIndexCreationTask<Product, Products_ByCategory.Result>' is less accessible than class 'Products_ByCategory'
> 
> It seems I need to remove "public" from Products_ByCategory class to make it work

...the problem is that I copied the Model classes (Product and Category) which are not set to public

**Comment by ayende** [comment]
Thanks, fixed.
